/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home/index`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login/styles` | `/login/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in/styles` | `/sign-in/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up/styles` | `/sign-up/styles`; params?: Router.UnknownInputParams; } | { pathname: `/@types/icons`; params?: Router.UnknownInputParams; } | { pathname: `/assets/icons/Icons`; params?: Router.UnknownInputParams; } | { pathname: `/styles/colors`; params?: Router.UnknownInputParams; } | { pathname: `/styles/font-family`; params?: Router.UnknownInputParams; } | { pathname: `/styles/theme`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/home/index`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/home/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login/styles` | `/login/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in/styles` | `/sign-in/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up/styles` | `/sign-up/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/@types/icons`; params?: Router.UnknownOutputParams; } | { pathname: `/assets/icons/Icons`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/font-family`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/theme`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/screens/home/index${`?${string}` | `#${string}` | ''}` | `/screens/home/styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login/styles${`?${string}` | `#${string}` | ''}` | `/login/styles${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in/styles${`?${string}` | `#${string}` | ''}` | `/sign-in/styles${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up/styles${`?${string}` | `#${string}` | ''}` | `/sign-up/styles${`?${string}` | `#${string}` | ''}` | `/@types/icons${`?${string}` | `#${string}` | ''}` | `/assets/icons/Icons${`?${string}` | `#${string}` | ''}` | `/styles/colors${`?${string}` | `#${string}` | ''}` | `/styles/font-family${`?${string}` | `#${string}` | ''}` | `/styles/theme${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home/index`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login/styles` | `/login/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in/styles` | `/sign-in/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up/styles` | `/sign-up/styles`; params?: Router.UnknownInputParams; } | { pathname: `/@types/icons`; params?: Router.UnknownInputParams; } | { pathname: `/assets/icons/Icons`; params?: Router.UnknownInputParams; } | { pathname: `/styles/colors`; params?: Router.UnknownInputParams; } | { pathname: `/styles/font-family`; params?: Router.UnknownInputParams; } | { pathname: `/styles/theme`; params?: Router.UnknownInputParams; };
    }
  }
}
